// components/mobile-nav.tsx
"use client";

import { type ReactElement, useCallback, useEffect, useState } from "react";
import { MdClose, MdMenu } from "react-icons/md";
import { navItems } from "../utils/nav-items";
import ActionButton from "./action-button";

interface LinkItemProps {
  name: string;
  href: string;
  close: () => void;
}

function LinkItem({ name, href, close }: LinkItemProps): ReactElement {
  return (
    <a
      href={href}
      onClick={close}
      className="uppercase font-bold hover:underline focus-visible:underline underline-offset-8 decoration-2 decoration-link-line"
    >
      {name}
    </a>
  );
}

export default function MobileNav(): ReactElement {
  const [collapsed, setCollapsed] = useState(true);
  const toggle = useCallback(() => {
    setCollapsed((current) => !current);
  }, []);
  const close = useCallback(() => {
    setCollapsed(true);
  }, []);

  useEffect(() => {
    if (collapsed) {
      return undefined;
    } else {
      const closeOnEscape = (event: KeyboardEvent) => {
        if (event.key === "Escape") {
          setCollapsed(true);
        }
      };
      window.addEventListener("keydown", closeOnEscape);
      return () => {
        window.removeEventListener("keydown", closeOnEscape);
      };
    }
  }, [collapsed]);

  const className = collapsed ? "hidden" : "";
  const linkItems = navItems.map((item) => (
    <LinkItem {...item} close={close} key={`${item.name}:${item.href}`} />
  ));
  const icon = collapsed ? <MdMenu /> : <MdClose />;
  return (
    <div className="fixed z-10 w-full md:hidden">
      <ActionButton
        label={collapsed ? "Open menu" : "Close menu"}
        expanded={!collapsed}
        onClick={toggle}
        className="absolute m-6 z-50 bg-menu text-menu-ink"
      >
        {icon}
      </ActionButton>
      <div
        className={`absolute h-dvh w-full z-40 flex flex-col justify-center items-center space-y-2 bg-ground text-ink text-xl ${className}`}
      >
        {linkItems}
      </div>
    </div>
  );
}

// src/lib/components/mobile-nav.svelte
<script lang="ts">
  import MdClose from "~icons/ic/baseline-close";
  import MdMenu from "~icons/ic/baseline-menu";
  import { navItems } from "../nav-items";
  import ActionButton from "./action-button.svelte";

  let collapsed = $state(true);

  function closeOnEscape(event: KeyboardEvent): void {
    if (event.key === "Escape") {
      collapsed = true;
    }
  }
</script>

<svelte:window onkeydown={closeOnEscape} />

<div class="fixed z-10 w-full md:hidden">
  <ActionButton
    label={collapsed ? "Open menu" : "Close menu"}
    expanded={!collapsed}
    onclick={() => {
      collapsed = !collapsed;
    }}
    class="absolute m-6 z-50 bg-menu text-menu-ink"
  >
    {#if collapsed}
      <MdMenu />
    {:else}
      <MdClose />
    {/if}
  </ActionButton>
  <div
    class={[
      "absolute h-dvh w-full z-40 flex flex-col justify-center items-center space-y-2 bg-ground text-ink text-xl",
      collapsed && "hidden",
    ]}
  >
    {#each navItems as { name, href } (href)}
      <a
        {href}
        onclick={() => {
          collapsed = true;
        }}
        class="uppercase font-bold hover:underline focus-visible:underline underline-offset-8 decoration-2 decoration-link-line"
      >
        {name}
      </a>
    {/each}
  </div>
</div>
